namespace Terrasoft.Core.Process.Configuration
{

	using Newtonsoft.Json;
	using Newtonsoft.Json.Linq;
	using System;
	using System.Collections.Generic;
	using System.Collections.ObjectModel;
	using System.Globalization;
	using Terrasoft.Common;
	using Terrasoft.Common.Json;
	using Terrasoft.Core;
	using Terrasoft.Core.Configuration;
	using Terrasoft.Core.DB;
	using Terrasoft.Core.Entities;
	using Terrasoft.Core.Process;
	using Terrasoft.UI.WebControls.Controls;

	#region Class: AutoGeneratedPageUserTaskSchema

	/// <exclude/>
	public class AutoGeneratedPageUserTaskSchema : Terrasoft.Core.Process.ProcessUserTaskSchema
	{

		#region Constructors: Public

		public AutoGeneratedPageUserTaskSchema(ProcessUserTaskSchemaManager processUserTaskSchemaManager)
			: base(processUserTaskSchemaManager) {
		}

		public AutoGeneratedPageUserTaskSchema(ProcessUserTaskSchema source)
			: base(source) {
		}

		#endregion

		#region Methods: Protected

		protected override void InitializeProperties() {
			base.InitializeProperties();
			UId = new Guid("b5936328-09b2-45fd-b763-48d37c265644");
			RealUId = new Guid("b5936328-09b2-45fd-b763-48d37c265644");
			Name = "AutoGeneratedPageUserTask";
			CreatedInPackageId = new Guid("f69f6aca-d587-4abd-9a90-ac4521baf251");
			UsageType = ProcessSchemaUsageType.Advanced;
			ParametersEditPageSchemaUId = new Guid("5c56940b-cb14-4180-b327-1270d77ac486");
			ParametersEditPageSchemaV2UId = new Guid("258075cc-a251-463d-bfbd-46a592091e4a");
			DcmParametersEditPageSchemaV2UId = Guid.Empty;
			ZipExecuteBody = new byte[] { 31,139,8,0,0,0,0,0,4,0,117,143,207,10,194,48,12,135,207,238,41,138,167,13,134,47,48,4,69,118,232,109,168,195,115,233,178,45,232,82,105,82,116,136,239,110,7,254,67,240,150,252,190,36,31,89,205,177,85,105,73,226,199,202,33,137,110,22,154,203,225,44,99,154,101,234,150,204,190,145,90,170,202,59,11,204,53,131,223,27,62,214,130,39,20,4,94,172,155,230,201,62,27,233,52,182,113,68,96,5,29,229,42,34,148,113,103,123,24,76,173,155,87,48,85,177,205,138,228,158,252,21,104,18,240,198,202,1,165,159,104,42,61,114,174,172,139,249,85,226,129,31,151,230,109,32,66,234,114,181,235,221,165,188,130,13,19,169,76,7,209,244,198,241,41,241,1,138,196,131,4,79,170,53,39,134,98,254,0,70,238,153,90,25,1,0,0 };
			SerializeToDB = true;
			IsUserTask = true;
			IsPartial = true;
		}

		protected override void InitializeParameters() {
			base.InitializeParameters();
			SetParametersDefInheritance();
			Parameters.Add(CreateTitleParameter());
			Parameters.Add(CreateEntitySchemaUIdParameter());
			Parameters.Add(CreateRecommendationParameter());
			Parameters.Add(CreateEntityIdParameter());
			Parameters.Add(CreateButtonsParameter());
			Parameters.Add(CreateElementsParameter());
			Parameters.Add(CreateExtendedClientModuleParameter());
			Parameters.Add(CreateEntryPointIdParameter());
			Parameters.Add(CreatePressedButtonCodeParameter());
			Parameters.Add(CreateOwnerIdParameter());
			Parameters.Add(CreateShowExecutionPageParameter());
			Parameters.Add(CreateInformationOnStepParameter());
			Parameters.Add(CreateIsRunningParameter());
		}

		protected virtual ProcessSchemaParameter CreateTitleParameter() {
			return new ProcessSchemaParameter(SchemaManagerProvider) {
				UId = new Guid("2758432d-80ca-4538-98d9-a6da05c774b2"),
				Name = "Title",
				DataValueType = DataValueTypeManager.GetInstanceByName("LocalizableStringDataValueType"),
				ReferenceSchemaUId = Guid.Empty,
				IsResult = false,
				IsPerformer = false,
				IsValueSerializable = true,
				IsRequired = false,
				IsLazy = false
			};
		}

		protected virtual ProcessSchemaParameter CreateEntitySchemaUIdParameter() {
			return new ProcessSchemaParameter(SchemaManagerProvider) {
				UId = new Guid("cabd6ac4-3578-4cd8-b075-aa92ad70a4a2"),
				Name = "EntitySchemaUId",
				DataValueType = DataValueTypeManager.GetInstanceByName("Lookup"),
				ReferenceSchemaUId = new Guid("2e155463-3ff1-4ccf-8584-4ec8d7233111"),
				IsResult = false,
				IsPerformer = false,
				IsValueSerializable = true,
				IsRequired = false,
				IsLazy = false
			};
		}

		protected virtual ProcessSchemaParameter CreateRecommendationParameter() {
			return new ProcessSchemaParameter(SchemaManagerProvider) {
				UId = new Guid("285caa41-719e-41d5-93dd-e0592ad15759"),
				Name = "Recommendation",
				DataValueType = DataValueTypeManager.GetInstanceByName("LocalizableStringDataValueType"),
				ReferenceSchemaUId = Guid.Empty,
				IsResult = false,
				IsPerformer = false,
				IsValueSerializable = true,
				IsRequired = false,
				IsLazy = false
			};
		}

		protected virtual ProcessSchemaParameter CreateEntityIdParameter() {
			return new ProcessSchemaParameter(SchemaManagerProvider) {
				UId = new Guid("2348f8c8-60d4-477a-b1a5-f57935d21264"),
				Name = "EntityId",
				DataValueType = DataValueTypeManager.GetInstanceByName("Lookup"),
				ReferenceSchemaUId = Guid.Empty,
				IsResult = false,
				IsPerformer = false,
				IsValueSerializable = true,
				IsRequired = false,
				IsLazy = false
			};
		}

		protected virtual ProcessSchemaParameter CreateButtonsParameter() {
			return new ProcessSchemaParameter(SchemaManagerProvider) {
				UId = new Guid("c06c5f05-0d52-4832-ab0f-89688bf8a3eb"),
				Name = "Buttons",
				DataValueType = DataValueTypeManager.GetInstanceByName("LocalizableStringDataValueType"),
				ReferenceSchemaUId = Guid.Empty,
				IsResult = false,
				IsPerformer = false,
				IsValueSerializable = true,
				IsRequired = false,
				IsLazy = false
			};
		}

		protected virtual ProcessSchemaParameter CreateElementsParameter() {
			return new ProcessSchemaParameter(SchemaManagerProvider) {
				UId = new Guid("95319dc0-1473-41d0-90a9-4b6f820f559a"),
				Name = "Elements",
				DataValueType = DataValueTypeManager.GetInstanceByName("LocalizableStringDataValueType"),
				ReferenceSchemaUId = Guid.Empty,
				IsResult = false,
				IsPerformer = false,
				IsValueSerializable = true,
				IsRequired = false,
				IsLazy = false
			};
		}

		protected virtual ProcessSchemaParameter CreateExtendedClientModuleParameter() {
			return new ProcessSchemaParameter(SchemaManagerProvider) {
				UId = new Guid("54945c6e-b673-49f5-a7a5-f690aaa12903"),
				Name = "ExtendedClientModule",
				DataValueType = DataValueTypeManager.GetInstanceByName("MaxSizeText"),
				ReferenceSchemaUId = Guid.Empty,
				IsResult = false,
				IsPerformer = false,
				IsValueSerializable = true,
				IsRequired = false,
				IsLazy = false
			};
		}

		protected virtual ProcessSchemaParameter CreateEntryPointIdParameter() {
			return new ProcessSchemaParameter(SchemaManagerProvider) {
				UId = new Guid("da23637b-d3f7-476b-a021-5530de365ff7"),
				Name = "EntryPointId",
				DataValueType = DataValueTypeManager.GetInstanceByName("Guid"),
				ReferenceSchemaUId = Guid.Empty,
				IsResult = false,
				IsPerformer = false,
				IsValueSerializable = true,
				IsRequired = false,
				IsLazy = false
			};
		}

		protected virtual ProcessSchemaParameter CreatePressedButtonCodeParameter() {
			return new ProcessSchemaParameter(SchemaManagerProvider) {
				UId = new Guid("a191f1d3-c2ee-4aa9-9931-7d13927f9069"),
				Name = "PressedButtonCode",
				DataValueType = DataValueTypeManager.GetInstanceByName("Text"),
				ReferenceSchemaUId = Guid.Empty,
				IsResult = true,
				IsPerformer = false,
				IsValueSerializable = true,
				IsRequired = false,
				IsLazy = false
			};
		}

		protected virtual ProcessSchemaParameter CreateOwnerIdParameter() {
			return new ProcessSchemaParameter(SchemaManagerProvider) {
				UId = new Guid("764fae77-b972-49e0-ba4a-4b56f04315df"),
				Name = "OwnerId",
				DataValueType = DataValueTypeManager.GetInstanceByName("Lookup"),
				ReferenceSchemaUId = new Guid("16be3651-8fe2-4159-8dd0-a803d4683dd3"),
				IsResult = false,
				IsPerformer = true,
				IsValueSerializable = true,
				IsRequired = false,
				IsLazy = false
			};
		}

		protected virtual ProcessSchemaParameter CreateShowExecutionPageParameter() {
			return new ProcessSchemaParameter(SchemaManagerProvider) {
				UId = new Guid("c2c3cea9-9945-4184-b6cb-c11bec2bd93a"),
				Name = "ShowExecutionPage",
				DataValueType = DataValueTypeManager.GetInstanceByName("Boolean"),
				SourceValue = new ProcessSchemaParameterValue() {
					Source = ProcessSchemaParameterValueSource.ConstValue,
					Value = @"true",
					MetaPath = null,
					ModifiedInSchemaUId = new Guid("b5936328-09b2-45fd-b763-48d37c265644"),
				},
				ReferenceSchemaUId = Guid.Empty,
				IsResult = false,
				IsPerformer = false,
				IsValueSerializable = true,
				IsRequired = false,
				IsLazy = false
			};
		}

		protected virtual ProcessSchemaParameter CreateInformationOnStepParameter() {
			return new ProcessSchemaParameter(SchemaManagerProvider) {
				UId = new Guid("9bfc6aa1-d622-4b58-ba87-1fe63a3519eb"),
				Name = "InformationOnStep",
				DataValueType = DataValueTypeManager.GetInstanceByName("LocalizableStringDataValueType"),
				ReferenceSchemaUId = Guid.Empty,
				IsResult = false,
				IsPerformer = false,
				IsValueSerializable = true,
				IsRequired = false,
				IsLazy = false
			};
		}

		protected virtual ProcessSchemaParameter CreateIsRunningParameter() {
			return new ProcessSchemaParameter(SchemaManagerProvider) {
				UId = new Guid("f829490d-24d9-4afb-a3a0-8557e49331f2"),
				Name = "IsRunning",
				DataValueType = DataValueTypeManager.GetInstanceByName("Boolean"),
				ReferenceSchemaUId = Guid.Empty,
				IsResult = false,
				IsPerformer = false,
				IsValueSerializable = true,
				IsRequired = false,
				IsLazy = false
			};
		}

		protected override void InitializeMethods() {
			base.InitializeMethods();
			SetMethodsDefInheritance();
			Methods.Add(CreateGetResultParameterAllValuesMethod());
		}

		protected override void InitializeUsings() {
			Usings.Add(new SchemaUsing() {
				UId = new Guid("4535ceb2-8df9-4847-ac6e-0eb546d45c2b"),
				Name = "Terrasoft.Common.Json",
				Alias = "",
				CreatedInPackageId = new Guid("8faebbb4-6032-45a8-ace5-f8b3ded3b01d")
			});
		}

		protected virtual SchemaMethod CreateGetResultParameterAllValuesMethod() {
			SchemaMethod method = new SchemaMethod() {
				UId = new Guid("92325a8b-8aa6-4dc2-be65-fa2c434d9d61"),
				Name = "GetResultParameterAllValues",
				CreatedInSchemaUId = new Guid("b5936328-09b2-45fd-b763-48d37c265644"),
				CreatedInPackageId = new Guid("f69f6aca-d587-4abd-9a90-ac4521baf251"),
				ResultValueTypeName = "Dictionary<Guid, string>",
				IsOverride = true,
				IsCustom = true
			};
			method.Arguments.Add(new SchemaMethodArgument() {
				UId = new Guid("e8b42eb6-f1a9-418b-bee4-e210a7eec7d8"),
				Name = "userConnection",
				CreatedInSchemaUId = new Guid("b5936328-09b2-45fd-b763-48d37c265644"),
				ModifiedInSchemaUId = new Guid("b5936328-09b2-45fd-b763-48d37c265644"),
				Direction = Terrasoft.Common.ParameterDirection.Input,
				ValueTypeName = "UserConnection",
				CreatedInPackageId = new Guid("f69f6aca-d587-4abd-9a90-ac4521baf251")
			});
			method.Arguments.Add(new SchemaMethodArgument() {
				UId = new Guid("ab466da8-04e9-4c35-9fe9-8910348a9ad8"),
				Name = "schemaUserTask",
				CreatedInSchemaUId = new Guid("b5936328-09b2-45fd-b763-48d37c265644"),
				ModifiedInSchemaUId = new Guid("b5936328-09b2-45fd-b763-48d37c265644"),
				Direction = Terrasoft.Common.ParameterDirection.Input,
				ValueTypeName = "ProcessSchemaUserTask",
				CreatedInPackageId = new Guid("f69f6aca-d587-4abd-9a90-ac4521baf251")
			});
			method.ZipBody = new byte[] { 31,139,8,0,0,0,0,0,4,0,117,80,93,75,195,48,20,125,182,191,34,244,41,129,146,63,208,90,112,78,198,68,182,65,167,47,226,67,76,239,92,180,77,198,189,105,165,138,255,221,38,5,157,195,189,4,238,61,57,247,124,244,10,153,118,182,54,222,56,251,160,154,14,136,93,50,11,239,108,110,116,216,41,28,138,69,103,234,140,145,71,99,95,74,46,242,164,31,89,228,58,212,16,41,35,131,243,13,58,13,68,149,222,67,171,54,10,85,11,30,80,80,156,239,9,112,171,232,77,254,0,36,23,224,103,195,106,156,120,58,235,188,119,150,82,33,100,245,123,54,79,204,142,241,73,86,46,105,213,53,205,26,111,218,131,31,248,145,184,140,175,16,236,51,185,64,240,29,218,211,64,121,242,21,29,27,15,109,72,119,75,206,94,59,219,3,122,57,135,209,153,81,141,249,128,245,243,43,104,95,220,25,242,197,81,248,73,63,99,46,194,101,89,254,35,158,39,59,135,160,244,158,241,243,204,168,207,140,157,124,68,191,39,70,229,85,93,243,208,125,40,156,135,111,143,233,178,78,159,228,214,85,241,22,23,34,99,211,94,171,67,32,254,5,67,210,51,29,124,3,220,130,58,209,233,1,0,0 };
			return method;
		}

		#endregion

		#region Methods: Public

		public override object Clone() {
			return new AutoGeneratedPageUserTaskSchema(this);
		}

		public override void GetParentRealUIds(Collection<Guid> realUIds) {
			base.GetParentRealUIds(realUIds);
			realUIds.Add(new Guid("b5936328-09b2-45fd-b763-48d37c265644"));
		}

		public override void InitializePrimaryInfo() {
			InitializeProperties();
			base.InitializePrimaryInfo();
			InitializeLocalizableValues();
		}

		public override Dictionary<Guid, string> GetResultParameterAllValues(UserConnection userConnection, ProcessSchemaUserTask schemaUserTask) {
			var conditionValues = new Dictionary<Guid, string>();
			var sourceValue = ((ProcessSchemaParameter)schemaUserTask.Parameters.GetByName("Buttons")).SourceValue;
			if (string.IsNullOrEmpty(sourceValue.Value)) {
				return conditionValues;
			}
			var items = JsonConvert.DeserializeObject<List<Dictionary<string, object>>>(sourceValue.Value);
			foreach (Dictionary<string, object> item in items) {
				conditionValues.Add(new Guid(item["Id"].ToString()), item["caption"].ToString());
			}
			return conditionValues;
		}

		public override ProcessUserTask CreateProcessUserTask(UserConnection userConnection) {
			return new AutoGeneratedPageUserTask(userConnection) {
				SchemaUId = new Guid("b5936328-09b2-45fd-b763-48d37c265644")
			};
		}

		#endregion

	}

	#endregion

	#region Class: AutoGeneratedPageUserTask

	[DesignModeGroup(Name = "General", Position = 1, UseSolutionStorage = true, ResourceManager = "b593632809b245fdb76348d37c265644", CaptionResourceItem = "Parameters.EntitySchemaUId.Group", DescriptionResourceItem = "Parameters.EntitySchemaUId.Group")]
	[DesignModeProperty(Name = "Title", Group = "", ValuesProvider = "ProcessSchemaParameterValueProvider", Editor="xtype=processschemaparametervalueedit;dataProvider=processschemaparametervalueprovider", ResourceManager = "b593632809b245fdb76348d37c265644", CaptionResourceItem = "Parameters.Title.Caption", DescriptionResourceItem = "Parameters.Title.Caption", UseSolutionStorage = true)]
	[DesignModeProperty(Name = "EntitySchemaUId", Group = "General", ValuesProvider = "ProcessSchemaParameterValueProvider", Editor="xtype=processschemaparametervalueedit;dataProvider=processschemaparametervalueprovider", ResourceManager = "b593632809b245fdb76348d37c265644", CaptionResourceItem = "Parameters.EntitySchemaUId.Caption", DescriptionResourceItem = "Parameters.EntitySchemaUId.Caption", UseSolutionStorage = true)]
	[DesignModeProperty(Name = "Recommendation", Group = "General", ValuesProvider = "ProcessSchemaParameterValueProvider", Editor="xtype=processschemaparametervalueedit;dataProvider=processschemaparametervalueprovider", ResourceManager = "b593632809b245fdb76348d37c265644", CaptionResourceItem = "Parameters.Recommendation.Caption", DescriptionResourceItem = "Parameters.Recommendation.Caption", UseSolutionStorage = true)]
	[DesignModeProperty(Name = "EntityId", Group = "General", ValuesProvider = "ProcessSchemaParameterValueProvider", Editor="xtype=processschemaparametervalueedit;dataProvider=processschemaparametervalueprovider", ResourceManager = "b593632809b245fdb76348d37c265644", CaptionResourceItem = "Parameters.EntityId.Caption", DescriptionResourceItem = "Parameters.EntityId.Caption", UseSolutionStorage = true)]
	[DesignModeProperty(Name = "Buttons", Group = "", ValuesProvider = "ProcessSchemaParameterValueProvider", Editor="xtype=processschemaparametervalueedit;dataProvider=processschemaparametervalueprovider", ResourceManager = "b593632809b245fdb76348d37c265644", CaptionResourceItem = "Parameters.Buttons.Caption", DescriptionResourceItem = "Parameters.Buttons.Caption", UseSolutionStorage = true)]
	[DesignModeProperty(Name = "Elements", Group = "", ValuesProvider = "ProcessSchemaParameterValueProvider", Editor="xtype=processschemaparametervalueedit;dataProvider=processschemaparametervalueprovider", ResourceManager = "b593632809b245fdb76348d37c265644", CaptionResourceItem = "Parameters.Elements.Caption", DescriptionResourceItem = "Parameters.Elements.Caption", UseSolutionStorage = true)]
	[DesignModeProperty(Name = "ExtendedClientModule", Group = "", ValuesProvider = "ProcessSchemaParameterValueProvider", Editor="xtype=processschemaparametervalueedit;dataProvider=processschemaparametervalueprovider", ResourceManager = "b593632809b245fdb76348d37c265644", CaptionResourceItem = "Parameters.ExtendedClientModule.Caption", DescriptionResourceItem = "Parameters.ExtendedClientModule.Caption", UseSolutionStorage = true)]
	[DesignModeProperty(Name = "EntryPointId", Group = "", ValuesProvider = "ProcessSchemaParameterValueProvider", Editor="xtype=processschemaparametervalueedit;dataProvider=processschemaparametervalueprovider", ResourceManager = "b593632809b245fdb76348d37c265644", CaptionResourceItem = "Parameters.EntryPointId.Caption", DescriptionResourceItem = "Parameters.EntryPointId.Caption", UseSolutionStorage = true)]
	[DesignModeProperty(Name = "PressedButtonCode", Group = "", ValuesProvider = "ProcessSchemaParameterValueProvider", Editor="xtype=processschemaparametervalueedit;dataProvider=processschemaparametervalueprovider", ResourceManager = "b593632809b245fdb76348d37c265644", CaptionResourceItem = "Parameters.PressedButtonCode.Caption", DescriptionResourceItem = "Parameters.PressedButtonCode.Caption", UseSolutionStorage = true)]
	[DesignModeProperty(Name = "OwnerId", Group = "General", ValuesProvider = "ProcessSchemaParameterValueProvider", Editor="xtype=processschemaparametervalueedit;dataProvider=processschemaparametervalueprovider", ResourceManager = "b593632809b245fdb76348d37c265644", CaptionResourceItem = "Parameters.OwnerId.Caption", DescriptionResourceItem = "Parameters.OwnerId.Caption", UseSolutionStorage = true)]
	[DesignModeProperty(Name = "ShowExecutionPage", Group = "", ValuesProvider = "ProcessSchemaParameterValueProvider", Editor="xtype=processschemaparametervalueedit;dataProvider=processschemaparametervalueprovider", ResourceManager = "b593632809b245fdb76348d37c265644", CaptionResourceItem = "Parameters.ShowExecutionPage.Caption", DescriptionResourceItem = "Parameters.ShowExecutionPage.Caption", UseSolutionStorage = true)]
	[DesignModeProperty(Name = "InformationOnStep", Group = "General", ValuesProvider = "ProcessSchemaParameterValueProvider", Editor="xtype=processschemaparametervalueedit;dataProvider=processschemaparametervalueprovider", ResourceManager = "b593632809b245fdb76348d37c265644", CaptionResourceItem = "Parameters.InformationOnStep.Caption", DescriptionResourceItem = "Parameters.InformationOnStep.Caption", UseSolutionStorage = true)]
	[DesignModeProperty(Name = "IsRunning", Group = "", ValuesProvider = "ProcessSchemaParameterValueProvider", Editor="xtype=processschemaparametervalueedit;dataProvider=processschemaparametervalueprovider", ResourceManager = "b593632809b245fdb76348d37c265644", CaptionResourceItem = "Parameters.IsRunning.Caption", DescriptionResourceItem = "Parameters.IsRunning.Caption", UseSolutionStorage = true)]
	/// <exclude/>
	public partial class AutoGeneratedPageUserTask : ProcessUserTask
	{

		#region Constructors: Public

		public AutoGeneratedPageUserTask(UserConnection userConnection)
			: base(userConnection) {
			SchemaUId = new Guid("b5936328-09b2-45fd-b763-48d37c265644");
		}

		#endregion

		#region Properties: Public

		private LocalizableString _title;
		public virtual LocalizableString Title {
			get {
				return _title ?? (_title = new LocalizableString());
			}
			set {
				_title = value;
			}
		}

		public virtual Guid EntitySchemaUId {
			get;
			set;
		}

		private LocalizableString _recommendation;
		public virtual LocalizableString Recommendation {
			get {
				return _recommendation ?? (_recommendation = new LocalizableString());
			}
			set {
				_recommendation = value;
			}
		}

		public virtual Guid EntityId {
			get;
			set;
		}

		private LocalizableString _buttons;
		public virtual LocalizableString Buttons {
			get {
				return _buttons ?? (_buttons = new LocalizableString());
			}
			set {
				_buttons = value;
			}
		}

		private LocalizableString _elements;
		public virtual LocalizableString Elements {
			get {
				return _elements ?? (_elements = new LocalizableString());
			}
			set {
				_elements = value;
			}
		}

		public virtual string ExtendedClientModule {
			get;
			set;
		}

		public virtual Guid EntryPointId {
			get;
			set;
		}

		public virtual string PressedButtonCode {
			get;
			set;
		}

		public virtual Guid OwnerId {
			get;
			set;
		}

		private bool _showExecutionPage = true;
		public virtual bool ShowExecutionPage {
			get {
				return _showExecutionPage;
			}
			set {
				_showExecutionPage = value;
			}
		}

		private LocalizableString _informationOnStep;
		public virtual LocalizableString InformationOnStep {
			get {
				return _informationOnStep ?? (_informationOnStep = new LocalizableString());
			}
			set {
				_informationOnStep = value;
			}
		}

		public virtual bool IsRunning {
			get;
			set;
		}

		#endregion

		#region Methods: Public

		public override void WritePropertiesData(DataWriter writer) {
			writer.WriteStartObject(Name);
			base.WritePropertiesData(writer);
			if (Status == Core.Process.ProcessStatus.Inactive) {
				writer.WriteFinishObject();
				return;
			}
			if (!HasMapping("EntitySchemaUId")) {
				writer.WriteValue("EntitySchemaUId", EntitySchemaUId, Guid.Empty);
			}
			if (!HasMapping("EntityId")) {
				writer.WriteValue("EntityId", EntityId, Guid.Empty);
			}
			if (!HasMapping("ExtendedClientModule")) {
				writer.WriteValue("ExtendedClientModule", ExtendedClientModule, null);
			}
			if (!HasMapping("EntryPointId")) {
				writer.WriteValue("EntryPointId", EntryPointId, Guid.Empty);
			}
			if (!HasMapping("PressedButtonCode")) {
				writer.WriteValue("PressedButtonCode", PressedButtonCode, null);
			}
			if (!HasMapping("OwnerId")) {
				writer.WriteValue("OwnerId", OwnerId, Guid.Empty);
			}
			if (!HasMapping("ShowExecutionPage")) {
				writer.WriteValue("ShowExecutionPage", ShowExecutionPage, false);
			}
			if (!HasMapping("IsRunning")) {
				writer.WriteValue("IsRunning", IsRunning, false);
			}
			writer.WriteFinishObject();
		}

		public override bool TryGetPerformer(out Guid performerUId) {
			performerUId = OwnerId;
			return true;
		}

		#endregion

		#region Methods: Protected

		protected override void ApplyPropertiesDataValues(DataReader reader) {
			base.ApplyPropertiesDataValues(reader);
			switch (reader.CurrentName) {
				case "Title":
					Title = reader.GetLocalizableStringValue();
				break;
				case "EntitySchemaUId":
					EntitySchemaUId = reader.GetGuidValue();
				break;
				case "Recommendation":
					Recommendation = reader.GetLocalizableStringValue();
				break;
				case "EntityId":
					EntityId = reader.GetGuidValue();
				break;
				case "Buttons":
					Buttons = reader.GetLocalizableStringValue();
				break;
				case "Elements":
					Elements = reader.GetLocalizableStringValue();
				break;
				case "ExtendedClientModule":
					ExtendedClientModule = reader.GetStringValue();
				break;
				case "EntryPointId":
					EntryPointId = reader.GetGuidValue();
				break;
				case "PressedButtonCode":
					PressedButtonCode = reader.GetStringValue();
				break;
				case "OwnerId":
					OwnerId = reader.GetGuidValue();
				break;
				case "ShowExecutionPage":
					ShowExecutionPage = reader.GetBoolValue();
				break;
				case "InformationOnStep":
					InformationOnStep = reader.GetLocalizableStringValue();
				break;
				case "IsRunning":
					IsRunning = reader.GetBoolValue();
				break;
			}
		}

		#endregion

	}

	#endregion

}

